CREATE TABLE tb_tipo_equipamento (
  ID_TIPO_EQUIPAMENTO INT(11) AUTO_INCREMENT NOT NULL,
  NOME VARCHAR(80) NOT NULL,
  PRIMARY KEY (ID_TIPO_EQUIPAMENTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tb_equipamento(
  ID_EQUIPAMENTO INT(11) AUTO_INCREMENT NOT NULL,
  NOME VARCHAR(80) NOT NULL,
  CODIGO VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  DATA_MOVIMENTACAO DATE DEFAULT NULL,
  STATUS VARCHAR(15) NOT NULL,
  ID_TIPO_EQUIPAMENTO INT(11) NOT NULL,
  PRIMARY KEY (ID_EQUIPAMENTO),
  CONSTRAINT FK_TIPO_EQUIPAMENTO FOREIGN KEY (ID_TIPO_EQUIPAMENTO) REFERENCES tb_tipo_equipamento (ID_TIPO_EQUIPAMENTO) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tb_equipamento_aluno(
  ID_EQUIP_ALUNO INT(11) AUTO_INCREMENT NOT NULL,
  ID_EQUIPAMENTO INT(11) NOT NULL,
  ID_USUARIO INT(11) NOT NULL,
  OBSERVACAO VARCHAR(255),
  PRIMARY KEY (ID_EQUIP_ALUNO),
  CONSTRAINT fk_id_equipamento FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES tb_equipamento (ID_EQUIPAMENTO) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_id_usuario FOREIGN KEY (ID_USUARIO) REFERENCES tb_usuario (ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
alter table tb_tipo_equipamento add status VARCHAR(15) NOT NULL