--liquibase formatted sql
--changeset andre:6
--comment criação da tabela aula e presença
  
CREATE TABLE tb_aula (
ID_AULA int(11) NOT NULL AUTO_INCREMENT,
DATA datetime DEFAULT NULL,
STATUS varchar(20) NOT NULL,
OBSERVACAO varchar(200) DEFAULT NULL,
ID_TURMA int(11) NOT NULL,
DT_INCLUSAO datetime DEFAULT NULL,
PRIMARY KEY (ID_AULA),
KEY fk_aula_idx (ID_AULA),
  CONSTRAINT fk_turmaf_u FOREIGN KEY (ID_TURMA) REFERENCES tb_turma (ID_TURMA) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;


CREATE TABLE tb_presenca (
ID_AULA int(11) NOT NULL,
ID_ALUNO int(11) NOT NULL,
MATRICULA VARCHAR(45) NOT NULL,
ID_TURMA int(11) NOT NULL,
STATUS varchar(20) NOT NULL,
PRIMARY KEY (ID_AULA,ID_ALUNO,MATRICULA,ID_TURMA),
KEY fk_aulapre_idx (ID_AULA),
  CONSTRAINT fk_aulapr_u FOREIGN KEY (ID_AULA) REFERENCES tb_aula (ID_AULA) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_alunopr_u FOREIGN KEY (ID_ALUNO) REFERENCES tb_turma_aluno (ID_ALUNO) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_matriculapr_u FOREIGN KEY (MATRICULA) REFERENCES tb_turma_aluno (MATRICULA) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_turmapr_u FOREIGN KEY (ID_TURMA) REFERENCES tb_turma_aluno (ID_TURMA) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
